name: API call example

on:  workflow_dispatch

jobs:
  call-api-and-trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Make API Call
      run:  |
        API_URL="https://dummyjson.com/products/1"
        API_TOKEN=$YOUR_SECRET_API_TOKEN  # Replace with the secret name

        # Make the API call using curl
        curl -X POST $API_URL
